# .streamlit/config.toml

[theme]
# Set the default theme here. Use "light" or "dark".
base="light"

# Theme colors for light mode
primaryColor="#1E90FF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"

# Theme colors for dark mode
[theme.dark]
primaryColor="#1E90FF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FFFFFF"
font="sans serif"
